spring:
  datasource:
    url: jdbc:mysql://192.168.101.6:3306/hiadt?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMultiQueries=true
    username: root
    password: admin
  jpa:
    generate-ddl: on
    show-sql: on
    hibernate:
      ddl-auto: update
    open-in-view: off
logging:
  level:
    org.springframework.web.servlet.resource.PathResourceResolver: INFO
