spring:
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/barbershop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: admin
  jpa:
    generate-ddl: on
    show-sql: on
    hibernate:
      ddl-auto: update
    open-in-view: off
    properties:
      hibernate.jdbc.time_zone: Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://root:example@192.168.0.2:27017/barbershop?authSource=admin&authMechanism=SCRAM-SHA-1&retryWrites=false
logging:
  level:
    org.springframework.web.servlet.resource.PathResourceResolver: INFO
